# Maven Build + Deploy Pipeline
trigger:
- master  # or main

pool:
  name: Default  # Your self-hosted agent pool

stages:
# --------- BUILD STAGE ---------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Maven Build'
    pool:
      name: Default
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '24.0.2'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: CopyFiles@2
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'rahulshatty'
        publishLocation: 'Container'

# --------- DEPLOY STAGE ---------
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy WAR'
    pool:
      name: Default
    steps:
    - download: current
      artifact: rahulshatty

    - script: |
        echo Deploying WAR file...
        REM Adjust the path to your Tomcat webapps folder
        set SRC=%AGENT_WORKSPACE%\_work\3\rahulshatty\*.war
        set DEST=C:\tomcat\webapps\
        echo Copying %SRC% to %DEST%
        copy %SRC% %DEST%
      displayName: 'Copy WAR to Deployment Server'

    - script: dir "%AGENT_WORKSPACE%\_work\3\rahulshatty"
      displayName: 'List downloaded artifact'
