trigger:
  branches:
    include:
      - master

pool:
  name: Default   # Self-hosted Windows agent

stages:
# --------- BUILD STAGE ---------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Maven Build'
    pool:
      name: Default
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '24.0.2'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      displayName: 'Copy WAR to staging'
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish WAR as Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'rahulshetty'
        publishLocation: 'Container'

# --------- DEPLOY STAGE ---------
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure WebApp'
    pool:
      name: Default
    steps:
    - download: current
      artifact: rahulshetty

    - task: AzureWebApp@1
      displayName: 'Deploy WAR to Azure Web App'
      inputs:
        azureSubscription: 'Azure subscription 1(905c3372-28e9-46c9-9959-66131db0ca93)'
        appType: 'webApp'
        appName: 'SanthoshVignesh2701'
        package: '$(System.DefaultWorkingDirectory)/**/*.war'
