trigger:
  branches:
    include:
      - master

pool:
  name: Default   # Self-hosted Windows agent

stages:
# --------- BUILD STAGE ---------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Maven Build'
    pool:
      name: Default
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '24.0.2'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: CopyFiles@2
      displayName: 'Copy WAR to staging'
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish WAR as Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'rahulshtty'
        publishLocation: 'Container'

# --------- DEPLOY TO STAGING ---------
- stage: Deploy_Staging
  displayName: 'Deploy to Staging'
  dependsOn: Build
  jobs:
  - job: DeployStaging
    displayName: 'Deploy WAR to Staging WebApp'
    pool:
      name: Default
    steps:
    - download: current
      artifact: rahulshtty

    - task: AzureWebApp@1
      displayName: 'Deploy WAR to Azure Web App (Staging)'
      inputs:
        azureSubscription: 'Azure subscription 1(905c3372-28e9-46c9-9959-66131db0ca93)'
        appType: 'webApp'
        appName: 'SanthoshVignesh2701'   # your staging webapp name
        package: C:\Users\santhosh k\Desktop\azure devops\vsts-agent-win-x64-4.261.0\_work\4\rahulshtty\webapp\target

# --------- TEST AFTER STAGING DEPLOY ---------
- stage: Test_Automation
  displayName: 'Run Automation Tests on Staging'
  dependsOn: Deploy_Staging
  jobs:
  - job: TestJob
    displayName: 'Run Automation Tests'
    pool:
      name: Default
    steps:
    # Example: Run Selenium/TestNG/JUnit tests
    - task: Maven@3
      displayName: 'Run Automation Tests'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    # Publish test results in Azure DevOps Tests tab
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        mergeTestResults: true
        failTaskOnFailedTests: true

# --------- DEPLOY TO PRODUCTION ---------
- stage: Deploy_Production
  displayName: 'Deploy to Production'
  dependsOn: Test_Automation
  condition: succeeded()   # only runs if tests passed
  jobs:
  - job: DeployProd
    displayName: 'Deploy WAR to Production WebApp'
    pool:
      name: Default
    steps:
    - download: current
      artifact: rahulshtty

    - task: AzureWebApp@1
      displayName: 'Deploy WAR to Azure Web App (Production)'
      inputs:
        azureSubscription: 'Azure subscription 1(905c3372-28e9-46c9-9959-66131db0ca93)'
        appType: 'webApp'
        appName: 'SanthoshVignesh2701'   # your production webapp name
        package: C:\Users\santhosh k\Desktop\azure devops\vsts-agent-win-x64-4.261.0\_work\4\rahulshtty\webapp\target
